top_srcdir   = /home/bill/APG/testcase/cve_21773/httpd-2.4.49
top_builddir = /home/bill/APG/testcase/cve_21773/httpd-2.4.49
srcdir       = /home/bill/APG/testcase/cve_21773/httpd-2.4.49/modules/generators
builddir     = /home/bill/APG/testcase/cve_21773/httpd-2.4.49/modules/generators
VPATH        = /home/bill/APG/testcase/cve_21773/httpd-2.4.49/modules/generators

include $(top_srcdir)/build/special.mk

