top_srcdir   = /home/bill/APG/testcase/cve_21773/httpd-2.4.49
top_builddir = /home/bill/APG/testcase/cve_21773/httpd-2.4.49
srcdir       = /home/bill/APG/testcase/cve_21773/httpd-2.4.49/os/unix
builddir     = /home/bill/APG/testcase/cve_21773/httpd-2.4.49/os/unix
VPATH        = /home/bill/APG/testcase/cve_21773/httpd-2.4.49/os/unix

LTLIBRARY_NAME    = libos.la
LTLIBRARY_SOURCES = unixd.c

include $(top_srcdir)/build/ltlib.mk
