top_srcdir   = /home/bill/APG/testcase/cve_21773/httpd-2.4.49
top_builddir = /home/bill/APG/testcase/cve_21773/httpd-2.4.49
srcdir       = /home/bill/APG/testcase/cve_21773/httpd-2.4.49/modules/aaa
builddir     = /home/bill/APG/testcase/cve_21773/httpd-2.4.49/modules/aaa
VPATH        = /home/bill/APG/testcase/cve_21773/httpd-2.4.49/modules/aaa

include $(top_srcdir)/build/special.mk

