top_srcdir   = /home/bill/APG/testcase/cve_21773/httpd-2.4.49
top_builddir = /home/bill/APG/testcase/cve_21773/httpd-2.4.49
srcdir       = /home/bill/APG/testcase/cve_21773/httpd-2.4.49/modules/core
builddir     = /home/bill/APG/testcase/cve_21773/httpd-2.4.49/modules/core
VPATH        = /home/bill/APG/testcase/cve_21773/httpd-2.4.49/modules/core

include $(top_srcdir)/build/special.mk

