top_srcdir   = /home/bill/APG/testcase/cve_21773/httpd-2.4.49
top_builddir = /home/bill/APG/testcase/cve_21773/httpd-2.4.49
srcdir       = /home/bill/APG/testcase/cve_21773/httpd-2.4.49/modules/debugging
builddir     = /home/bill/APG/testcase/cve_21773/httpd-2.4.49/modules/debugging
VPATH        = /home/bill/APG/testcase/cve_21773/httpd-2.4.49/modules/debugging
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
